version: "2"
services:
  php:
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/html
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes_from:
      - php
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  mock:
    image: stoplight/prism:latest
    command: "mock -h 0.0.0.0 /tmp/specs/static-example.yaml"
    volumes:
      - ./packages/php-openapi-faker/tests/specs:/tmp/specs:ro
    ports:
      - "4010:4010"
